name: "CI"

on:
  [push, pull_request]

jobs:

  server:

    runs-on: ubuntu-latest

    services:
      redis:
          image: redis:alpine
          ports:
              - "6379:6379"

      mongo:
          image: mongo:4.4
          ports:
              - "27017:27017"

      elastic:
          image: elasticsearch:7.17.23
          ports:
              - "9200:9200"
          env:
            discovery.type: single-node

    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - run: sudo apt-get update
    - run: sudo apt-get -y install libxmlsec1-dev

    - run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r dev-requirements.txt

    - run: flake8

    - run: mypy .

    - run: nosetests

    - run: behave ./features/ --format progress2 --logging-level ERROR

    - run: python manage.py app:initialize_data


  client:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 14
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - run: npm ci

    - run: npm test

    - run: npm run build
